[profile.default]
src = "src/Seedify"
out = "out"
libs = ["lib"]

[rpc_endpoints]
open_campus = "${RPC_URL}"

[etherscan]
open_campus = { key = "${API_KEY}", url = "https://opencampus.gelatoscout.com/api" }
